# Generated by Django 5.2.7 on 2025-10-09 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.PositiveIntegerField(default=0, help_text='File size in bytes'),
        ),
        migrations.AddField(
            model_name='document',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='chat.chatsession'),
        ),
    ]
